ktor {
  application {
    modules = [ si.sensum.backend.ApplicationKt.module ]
  }

  deployment {
    port = ${?BACKEND_CORE_PORT}
    port = 8082

    host = ${?BACKEND_CORE_HOST}
    host = "0.0.0.0"
  }
}