ktor {
  application {
    modules = [ si.sensum.backend.ApplicationKt.module ]
  }

  deployment {
    port = 8082
    port = ${?BACKEND_CORE_PORT}

    host = "0.0.0.0"
    host = ${?BACKEND_CORE_HOST}
  }
}

database {
  jdbcUrl = "jdbc:postgresql://localhost:5432/sensum"
  jdbcUrl = ${?BACKEND_CORE_DB_JDBC_URL}

  user = "sensum"
  user = ${?BACKEND_CORE_DB_USER}

  password = "sensum"
  password = ${?BACKEND_CORE_DB_PASSWORD}
}

gm {
  baseUrl = "http://localhost:8081"
  baseUrl = ${?GM_BASE_URL}

  apiAuthToken = "dev-gm-token"
  apiAuthToken = ${?GM_API_AUTH_TOKEN}
}

sws {
  username = ${?SWS_USERNAME}
  password = ${?SWS_PASSWORD}
}