ktor {
  application {
    modules = [ si.sensum.gm.ApplicationKt.module ]
  }

  deployment {
    port = 8081
    port = ${?GM_PORT}

    host = "0.0.0.0"
    host = ${?GM_HOST}
  }
}

gm {
  auth {
    tokenTtlHours = 8
    tokenTtlHours = ${?GM_AUTH_TOKEN_TTL_HOURS}

    apiToken = "change-this-dev-token"
    apiToken = ${?GM_API_AUTH_TOKEN}
  }
}

sws {
  baseUrl = "https://smart.eltratec.com/SmartWebDev/SmartWebService.asmx"
  baseUrl = ${?SWS_BASE_URL}

  timeoutMillis = 10000
  timeoutMillis = ${?SWS_TIMEOUT_MILLIS}
}