ktor {
  application {
    modules = [ si.sensum.gm.ApplicationKt.module ]
  }

  deployment {
    port = ${?GM_PORT}
    port = 8081

    host = ${?GM_HOST}
    host = "0.0.0.0"
  }
}

gm {
  auth {
    tokenTtlHours = ${?GM_AUTH_TOKEN_TTL_HOURS}
    tokenTtlHours = 8
  }
}

sws {
  baseUrl = ${?SWS_BASE_URL}
  baseUrl = ""

  timeoutMillis = ${?SWS_TIMEOUT_MILLIS}
  timeoutMillis = 10000
}