ktor {
  application {
    modules = [ si.sensum.api.ApplicationKt.module ]
  }

  deployment {
    port = 8080
    port = ${?API_GATEWAY_PORT}

    host = "0.0.0.0"
    host = ${?API_GATEWAY_HOST}
  }
}

gm {
  baseUrl = "http://localhost:8081"
  baseUrl = ${?GM_BASE_URL}

  authToken = "change-this-dev-token"
  authToken = ${?GM_API_AUTH_TOKEN}
}