ktor {
  application {
    modules = [ si.sensum.api.ApplicationKt.module ]
  }

  deployment {
    port = 8080
    port = ${?API_GATEWAY_PORT}

    host = "0.0.0.0"
    host = ${?API_GATEWAY_HOST}
  }
}

backendCore {
  baseUrl = "http://localhost:8082"
  baseUrl = ${?BACKEND_CORE_BASE_URL}
}

auth {
  username = "sensum"
  username = ${?API_AUTH_USERNAME}

  password = "sensum"
  password = ${?API_AUTH_PASSWORD}
}

jwt {
  secret = "local-development-jwt-secret-change-this-32-chars"
  secret = ${?JWT_SECRET}

  issuer = "sensum-api-gateway"
  issuer = ${?JWT_ISSUER}

  audience = "sensum-clients"
  audience = ${?JWT_AUDIENCE}

  realm = "sensum-api"
  realm = ${?JWT_REALM}

  ttlSeconds = 3600
  ttlSeconds = ${?JWT_TTL_SECONDS}
}